name: Build and Push Multi-Arch Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push multi-arch Docker image
      env:
        DOCKER_IMAGE_TAG: ${{ github.ref }}
      run: |
        docker buildx create --use --name mybuilder --use
        docker buildx inspect mybuilder --bootstrap
        docker buildx build --push --platform linux/amd64,linux/arm64,linux/arm64/v8 \
          --tag ghcr.io/jacobfg/rss_proxy:${DOCKER_IMAGE_TAG#refs/tags/} \
          .

    - name: Clean up
      run: |
        docker buildx stop mybuilder
